### ISSUE TITLE
ColorPicker's visible size doesn't the real touch size

### ISSUE THREAD

**Issue by Xin-1027** [Exidel/Color_Picker#1]
ColorPicker's visible size doesn't the real touch size

**Comment by Exidel** [comment]
Just checked it out. All rects clickable inside their bounds.
Can you explain this issue a bit more accurate and share a small repro? Also do you use it on desktop with mouse or may be on device with touchpad?

**Comment by Exidel** [comment]
@HongZhi-d 
So I'm checked it on Android emulator and it's work diffirent cos I didn't use LocalDensity to get real size for current device screen.
About color and alpha rect on Android: 
Under Windows system all events happeneds inside rect bounds, 
Under Android system it force space around interactive element to be minimum 48px to match Material Design Accessibility guidelines. And I didn't rly find a way to remove or change it.
